name: Build and publish Ente server tools

on: [push]

jobs:
    publish:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Build and push
              uses: mr-smithers-excellent/docker-build-push@v6
              with:
                  dockerfile: images/ente-server-tools/Dockerfile
                  image: ente-server-tools
                  registry: ghcr.io
                  enableBuildKit: true
                  tags: latest
                  username: ${{ github.actor }}
                  password: ${{ secrets.GITHUB_TOKEN }}
